### ISSUE TITLE
Use icon in header search bar

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb-theme#14]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5046827648

---

In the search bar in the header, use an icon instead of text for search. 
To do this, replace this html

```html
<input class="btn btn-default button js-form-submit form-submit btn-primary" data-drupal-selector="edit-submit" type="submit" id="edit-submit" name="op" value="Submit">
```
with

```html
<button class="btn btn-default button js-form-submit form-submit btn-primary" data-drupal-selector="edit-submit" type="submit" id="edit-submit" name="op" value="Submit"><i class="fa-solid fa-magnifying-glass"></i><span class="visually-hidden">search</span></button>
```

>**Note**: This change should happen in the base-build and be brought down to projects.

## screenshot
The search block should look like the one on the bottom

![image](https://github.com/bcgov/bcbb-theme/assets/3910508/f273c9e1-4279-4378-9ff7-e6e52fcd3cef)

**Comment by CraigClark** [comment]
When this is done, please show me. I'd like to know how to make this type of change

**Comment by lkmorlan** [comment]
This change was implemented by the theme change in this repository plus this change:
https://github.com/bcgov/bcbb/commit/0e9b9b23bb716dbb141eb01d6558989765070890

**Comment by CraigClark** [comment]
Reviewed and approved on dv21
