### ISSUE TITLE
Change appearance of login block in header

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb-theme#15]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5047437638

---

[Related issue in base-build repo](https://github.com/bcgov/bcbb/issues/28)

The following changes need to be made to the login block in the header.

>**Note**: These changes should be part of the base build and brought down to other projects. The CSS to support this is done.

## Remove Reset password

IDIR users don't reset their passwords in Drupal.

remove the following from the login block
```html

<div class="item-list"><ul><li><a href="/user/password" title="Send password reset instructions via email." class="request-password-link">Reset your password</a></li></ul></div>
```

## Appearance of login form

Change the classes on the login as follows:

```html

<input data-drupal-selector="edit-openid-connect-client-keycloak-login" type="submit" id="edit-openid-connect-client-keycloak-login" name="keycloak" value="Log in with IDIR" class="button js-form-submit form-submit btn btn-primary">

```

to

```html
<input data-drupal-selector="edit-openid-connect-client-keycloak-login" type="submit" id="edit-openid-connect-client-keycloak-login" name="keycloak" value="Log in with IDIR" class="js-form-submit form-submit bb-link-light">
```

## screenshots

When done, the login in the header should look like this

![image](https://github.com/bcgov/bcbb-theme/assets/3910508/6f1a4845-f14a-459e-bd7a-18b529f44843)

**Comment by lkmorlan** [comment]
Password reset link removed from login page in https://github.com/bcgov/bcbb/issues/28.

**Comment by lkmorlan** [comment]
Reset password link removed in:
https://github.com/bcgov/bcbb/commit/056f1ac22e4cfe84712f081975fb4c971d70c24c

**Comment by lkmorlan** [comment]
Code moved to new `bcbb_auth` module in:
https://github.com/bcgov/bcbb/commit/e4b290a60e192572f9d17b7cc642d5ff56a5730a

**Comment by CraigClark** [comment]
done on dv21
